name: Python application

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -v
    - name: Deploy to Render
      env:
        RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
        RENDER_PASSWORD: ${{ secrets.RENDER_PASSWORD }}
        RENDER_PROJECT_ID: your-project-id
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        render login --email $RENDER_EMAIL --password $RENDER_PASSWORD
        render up --project-id $RENDER_PROJECT_ID --force